name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  test-code:
    runs-on: ubuntu-22.04
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker login
        run: |
          echo $DOCKER_HUB_TOKEN > password.txt
          cat  password.txt | docker login --username yanhu12 --password-stdin
      - name: build image
        run: |
          docker image build -t yanhu12/fastapi-demo:latest .
      - name: push image
        run: |
          docker image push yanhu12/fastapi-demo:latest





